# docker-compose.yml
# version: '3.8'

services:
  postgres-db:
    image: postgis/postgis:15-3.3 # Use a PostGIS-enabled image
    container_name: civic_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: civic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis-cache:
    image: redis:7-alpine
    container_name: civic_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: